### ISSUE TITLE
missing favicon.ico

### ISSUE THREAD

**Issue by pascalpp** [StayWokeOrg/intake#16]
currently this 404s. perhaps we can come up with a standard icon for all projects to use.

**Comment by dougblackjr** [comment]
Created a pull request for this

**Comment by pascalpp** [comment]
for future, you can do `Fixes #16` in your PR description and it will put a reference on the ticket and auto-close it when the PR is merged.

**Comment by dougblackjr** [comment]
Thank you! That's good to know!
