### ISSUE TITLE
prevent 'undefined' string from being saved into db

### ISSUE THREAD

**Issue by pascalpp** [StayWokeOrg/intake#27]
![image](https://cloud.githubusercontent.com/assets/1355312/21919749/de51872a-d92a-11e6-8b28-232e01f9c5e3.png)

the string `'undefined'` should be `null` (not a string).

**Comment by mattstauffer** [comment]
@pascalpp Is this a thing where the JavaScript is posting "undefined" over to the API? (I assume so, since A) that's a normal javascript thing and B) you put this here instead of on central.. but just wanted to make sure)

**Comment by pascalpp** [comment]
yeah this is an intake problem. i think i just need to remove undefined keys in the posted data.
