### ISSUE TITLE
redirect http->https in production

### ISSUE THREAD

**Issue by pascalpp** [StayWokeOrg/intake#40]

**Comment by pascalpp** [comment]
for now probably going to do this in express, unless we can easily do it in nginx

http://expressjs.com/en/guide/using-middleware.html

**Comment by dougblackjr** [comment]
Addressed in pull request. Combined with favicon pull request (forgot to branch it off)

**Comment by pascalpp** [comment]
This isn't working afaict. Not sure what the issue is, but when I visit http://in.staywoketech.org it doesn't redirect to https.

**Comment by pascalpp** [comment]
Hmm I sorta got it working, by reorganizing the middleware setup, putting the production middleware first. When I deployed it and hit http://in.staywoketech.org, it does redirect to https://in.staywoketech.org, but then I get a `too many redirects` error:

![image](https://cloud.githubusercontent.com/assets/1355312/22004401/46d89e5e-dc29-11e6-95ff-cf0fa45517cf.png)

So will need someone with more express experience to have a look at this, I think.

**Comment by pascalpp** [comment]
we tried doing this with express-sslify, but that resulted in the too many redirects error shown above.

**Comment by jpetto** [comment]
@pascalpp - Is this still an issue? If so, and if you can provide hosting details (not necessarily access, but the setup), I can do some research.

**Comment by pascalpp** [comment]
we currently have a single host behind an load balancer, no nginx. (normally we'd do this in nginx, and we probably will later, but for now the decision is to just check each request in express and redirect `http://hostname/params` to `https://hostname/params`. me and doug have tried a couple different ways, but we're both new to express so haven't been able to get it working yet. (i work in an express stack daily, but mostly doing frontend stuff.)

**Comment by pascalpp** [comment]
@jpetto this is the middleware package we tried most recently: https://github.com/florianheinemann/express-sslify/blob/master/index.js#L45

**Comment by pascalpp** [comment]
if you can make a branch I can deploy it for testing and we can round trip.

**Comment by jpetto** [comment]
Cool - I'll do a bit of investigation and tinkering after work.
