### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by pascalpp** [StayWokeOrg/intake#8]
seems like we should implement https since we're collecting user data.

maybe we can use https://letsencrypt.org.

**Comment by meganrm** [comment]
https://expressjs.com/en/advanced/best-practice-security.html

**Comment by jpetto** [comment]
Filed #19 to add `helmet` middleware. Do we have hosting set up yet? Depending on the complexity there, I could configure letsencrypt.

**Comment by pascalpp** [comment]
@jpetto Can you own this ticket? We're still sorting out hosting. @mattstauffer is PMing this project so we can discuss hosting with him. I think the plan is to host at staywoke.org/in. Currently staywoke.org redirects to a typeform page on a different domain, so there might not be a current host in place.

**Comment by jpetto** [comment]
Yep, I can take this one. Happy to join hosting conversations, but my availability needn't slow things down. Should be good with whatever hosting solution.

**Comment by pascalpp** [comment]
@jpetto I'm working with @potatono and a coworker of mine to set up hosting at AWS. If we have questions about using letsencrypt I'll ping you here or in slack.

**Comment by jpetto** [comment]
@pascalpp Sounds good. If AWS is the answer, [AWS Cert Manager](https://aws.amazon.com/certificate-manager/) is probably easier than letsencrypt. Anyway, keep me posted!

**Comment by pascalpp** [comment]
status: figured out letsencrypt today with help from coworkers, and got certs for in.staywoketech.org and central.staywoke.org. and @potatono got the ELB set up with the certs and DNS. so i think we're good on this front. will set up redirects for staywoke.org when we launch.
